
// ignore_for_file: must_be_immutable

import 'package:flutter/material.dart';

import '../components/custom_tafsseir_card.dart';
import '../constants/colors.dart';
import '../models/sheikh_model.dart';

class TafsseirScreen extends StatelessWidget {
   TafsseirScreen({Key? key}) : super(key: key);
  static String id = 'TafsseirScreen';
  List<SheikhModel> tafsseirList = [
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/001.mp3" , suwraName : "سورة الفاتحة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-1-25.mp3" , suwraName : "سورة البقرة الايات من 1 الى 25"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-26-43.mp3" , suwraName : "سورة البقرة الايات من 26 الى 43"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-44-59.mp3" , suwraName : "سورة البقرة الايات من 44 الى 59"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-60-74.mp3" , suwraName : "سورة البقرة الايات من 60 الى 74"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-75-91.mp3" , suwraName : "سورة البقرة الايات من 75 الى 91"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-92-105.mp3" , suwraName : "سورة البقرة الايات من 92 الى 105"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-106-123.mp3" , suwraName : "سورة البقرة الايات من 106 الى 123"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-124-141.mp3" , suwraName : "سورة البقرة الايات من 124 الى 141"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-142-157.mp3" , suwraName : "سورة البقرة الايات من 142 الى 157"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-158-176.mp3" , suwraName : "سورة البقرة الايات من 158 الى 176"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-177-188.mp3" , suwraName : "سورة البقرة الايات من 177 الى 188"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-189-202.mp3" , suwraName : "سورة البقرة الايات من 189 الى 202"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-203-218.mp3" , suwraName : "سورة البقرة الايات من 203 الى 218"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-219-232.mp3" , suwraName : "سورة البقرة الايات من 219 الى 232"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-233-242.mp3" , suwraName : "سورة البقرة الايات من 233 الى 242"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-243-252.mp3" , suwraName : "سورة البقرة الايات من 243 الى 252"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-253-262.mp3" , suwraName : "سورة البقرة الايات من 253 الى 262"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-263-271.mp3" , suwraName : "سورة البقرة الايات من 263 الى 271"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-272-282.mp3" , suwraName : "سورة البقرة الايات من 272 الى 282"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/002-283-286.mp3" , suwraName : "سورة البقرة الايات من 283 الى 286"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-1-14.mp3" , suwraName : "سورة آل عمران الايات من 1 الى 14"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-15-32.mp3" , suwraName : "سورة آل عمران الايات من 15 الى 32"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-33-51.mp3" , suwraName : "سورة آل عمران الايات من 33 الى 51"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-52-74.mp3" , suwraName : "سورة آل عمران الايات من 52 الى 74"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-75-92.mp3" , suwraName : "سورة آل عمران الايات من 75 الى 92"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-93-112.mp3" , suwraName : "سورة آل عمران الايات من 93 الى 112"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-113-132.mp3" , suwraName : "سورة آل عمران الايات من 113 الى 132"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-133-152.mp3" , suwraName : "سورة آل عمران الايات من 133 الى 152"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-153-170.mp3" , suwraName : "سورة آل عمران الايات من 153 الى 170"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-171-185.mp3" , suwraName : "سورة آل عمران الايات من 171 الى 185"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/003-186-200.mp3" , suwraName : "سورة آل عمران الايات من 186 الى 200"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-1-11.mp3" , suwraName : "سورة النساء الايات من 1 الى 11"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-12-23.mp3" , suwraName : "سورة النساء الايات من 12 الى 23"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-24-35.mp3" , suwraName : "سورة النساء الايات من 24 الى 35"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-36-57.mp3" , suwraName : "سورة النساء الايات من 36 الى 57"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-58-73.mp3" , suwraName : "سورة النساء الايات من 58 الى 73"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-74-87.mp3" , suwraName : "سورة النساء الايات من 74 الى 87"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-88-99.mp3" , suwraName : "سورة النساء الايات من 88 الى 99"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-100-113.mp3" , suwraName : "سورة النساء الايات من 100 الى 113"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-114-134.mp3" , suwraName : "سورة النساء الايات من 114 الى 134"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-135-147.mp3" , suwraName : "سورة النساء الايات من 135 الى 147"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-148-162.mp3" , suwraName : "سورة النساء الايات من 148 الى 162"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/004-163-176.mp3" , suwraName : "سورة النساء الايات من 163 الى 176"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-1-11.mp3" , suwraName : "سورة المائدة الايات من 1 الى 11"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-12-26.mp3" , suwraName : "سورة المائدة الايات من 12 الى 26"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-27-40.mp3" , suwraName : "سورة المائدة الايات من 27 الى 40"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-41-50.mp3" , suwraName : "سورة المائدة الايات من 41 الى 50"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-51-66.mp3" , suwraName : "سورة المائدة الايات من 51 الى 66"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-67-81.mp3" , suwraName : "سورة المائدة الايات من 67 الى 81"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-82-96.mp3" , suwraName : "سورة المائدة الايات من 82 الى 96"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-97-108.mp3" , suwraName : "سورة المائدة الايات من 97 الى 108"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/005-109-120.mp3" , suwraName : "سورة المائدة الايات من 109 الى 120"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-1-12.mp3" , suwraName : "سورة الأنعام الايات من 1 الى 12"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-13-35.mp3" , suwraName : "سورة الأنعام الايات من 13 الى 35"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-36-58.mp3" , suwraName : "سورة الأنعام الايات من 36 الى 58"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-59-73.mp3" , suwraName : "سورة الأنعام الايات من 59 الى 73"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-74-94.mp3" , suwraName : "سورة الأنعام الايات من 74 الى 94"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-95-110.mp3" , suwraName : "سورة الأنعام الايات من 95 الى 110"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-111-126.mp3" , suwraName : "سورة الأنعام الايات من 111 الى 126"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-127-140.mp3" , suwraName : "سورة الأنعام الايات من 127 الى 140"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-141-150.mp3" , suwraName : "سورة الأنعام الايات من 141 الى 150"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/006-151-165.mp3" , suwraName : "سورة الأنعام الايات من 151 الى 165"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-1-30.mp3" , suwraName : "سورة الأعراف الايات من 1 الى 30"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-31-46.mp3" , suwraName : "سورة الأعراف الايات من 31 الى 46"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-47-64.mp3" , suwraName : "سورة الأعراف الايات من 47 الى 64"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-65-87.mp3" , suwraName : "سورة الأعراف الايات من 65 الى 87"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-88-116.mp3" , suwraName : "سورة الأعراف الايات من 88 الى 116"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-117-141.mp3" , suwraName : "سورة الأعراف الايات من 117 الى 141"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-142-155.mp3" , suwraName : "سورة الأعراف الايات من 142 الى 155"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-150-170.mp3" , suwraName : "سورة الأعراف الايات من 156 الى 170"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-171-188.mp3" , suwraName : "سورة الأعراف الايات من 171 الى 188"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/007-189-206.mp3" , suwraName : "سورة الأعراف الايات من 189 الى 206"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/008-1-21.mp3" , suwraName : "سورة الأنفال الايات من 1 الى 21"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/008-22-40.mp3" , suwraName : "سورة الأنفال الايات من 22 الى 40"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/008-41-60.mp3" , suwraName : "سورة الأنفال الايات من 41 الى 60"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/008-61-75.mp3" , suwraName : "سورة الأنفال الايات من 61 الى 75"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-1-18.mp3" , suwraName : "سورة التوبة الايات من 1 الى 18"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-19-33.mp3" , suwraName : "سورة التوبة الايات من 19 الى 33"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-34-45.mp3" , suwraName : "سورة التوبة الايات من 34 الى 45"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-46-59.mp3" , suwraName : "سورة التوبة الايات من 46 الى 59"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-60-74.mp3" , suwraName : "سورة التوبة الايات من 60 الى 74"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-75-92.mp3" , suwraName : "سورة التوبة الايات من 75 الى 92"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-93-110.mp3" , suwraName : "سورة التوبة الايات من 93 الى 110"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-111-121.mp3" , suwraName : "سورة التوبة الايات من 111 الى 121"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/009-122-129.mp3" , suwraName : "سورة التوبة الايات من 122 الى 129"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/010-1-10.mp3" , suwraName : "سورة يونس الايات من 1 الى 10"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/010-11-25.mp3" , suwraName : "سورة يونس الايات من 11 الى 25"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/010-26-52.mp3" , suwraName : "سورة يونس الايات من 26 الى 52"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/010-53-70.mp3" , suwraName : "سورة يونس الايات من 53 الى 70"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/010-71-89.mp3" , suwraName : "سورة يونس الايات من 71 الى 89"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/010-90-109.mp3" , suwraName : "سورة يونس الايات من 90 الى 109"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/011-1-5.mp3" , suwraName : "سورة هود الايات من 1 الى 5"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/011-6-23.mp3" , suwraName : "سورة هود الايات من 6 الى 23"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/011-24-40.mp3" , suwraName : "سورة هود الايات من 24 الى 40"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/011-41-60.mp3" , suwraName : "سورة هود الايات من 41 الى 60"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/011-61-83.mp3" , suwraName : "سورة هود الايات من 61 الى 83"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/011-84-107.mp3" , suwraName : "سورة هود الايات من 84 الى 107"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/011-108-123.mp3" , suwraName : "سورة هود الايات من 108 الى 123"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/012-1-6.mp3" , suwraName : "سورة يوسف الايات من 1 الى 6"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/012-7-29.mp3" , suwraName : "سورة يوسف الايات من 7 الى 29"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/012-30-52.mp3" , suwraName : "سورة يوسف الايات من 30 الى 52"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/012-53-76.mp3" , suwraName : "سورة يوسف الايات من 53 الى 76"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/012-77-100.mp3" , suwraName : "سورة يوسف الايات من 77 الى 100"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/012-101-111.mp3" , suwraName : "سورة يوسف الايات من 101 الى 111"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/013-1-4.mp3" , suwraName : "سورة الرعد الايات من 1 الى 4"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/013-5-18.mp3" , suwraName : "سورة الرعد الايات من 5 الى 18"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/013-19-34.mp3" , suwraName : "سورة الرعد الايات من 19 الى 34"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/013-35-43.mp3" , suwraName : "سورة الرعد الايات من 35 الى 43"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/014-1-9.mp3" , suwraName : "سورة إبراهيم الايات من 1 الى 9"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/014-10-27.mp3" , suwraName : "سورة إبراهيم الايات من 10 الى 27"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/014-28-52.mp3" , suwraName : "سورة إبراهيم الايات من 28 الى 52"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/015-1-48.mp3" , suwraName : "سورة الحجر الايات من 1 الى 48"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/015-49-99.mp3" , suwraName : "سورة الحجر الايات من 49 الى 99"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/016-1-29.mp3" , suwraName : "سورة النحل الايات من 1 الى 29"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/016-30-50.mp3" , suwraName : "سورة النحل الايات من 30 الى 50"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/016-51-74.mp3" , suwraName : "سورة النحل الايات من 51 الى 74"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/016-90-110.mp3" , suwraName : "سورة النحل الايات من 90 الى 110"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/016-111-128.mp3" , suwraName : "سورة النحل الايات من 111 الى 128"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/017-1-22.mp3" , suwraName : "سورة الإسراء الايات من 1 الى 22"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/017-23-49.mp3" , suwraName : "سورة الإسراء الايات من 23 الى 49"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/017-50-69.mp3" , suwraName : "سورة الإسراء الايات من 50 الى 69"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/017-70-98.mp3" , suwraName : "سورة الإسراء الايات من 70 الى 98"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/017-99-111.mp3" , suwraName : "سورة الإسراء الايات من 99 الى 111"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/018-1-16.mp3" , suwraName : "سورة الكهف الايات من 1 الى 16"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/018-17-31.mp3" , suwraName : "سورة الكهف الايات من 17 الى 31"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/018-32-50.mp3" , suwraName : "سورة الكهف الايات من 32 الى 50"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/018-51-74.mp3" , suwraName : "سورة الكهف الايات من 51 الى 74"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/018-75-98.mp3" , suwraName : "سورة الكهف الايات من 75 الى 98"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/018-99-110.mp3" , suwraName : "سورة الكهف الايات من 99 الى 110"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/019-1-21.mp3" , suwraName : "سورة مريم الايات من 1 الى 21"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/019-22-58.mp3" , suwraName : "سورة مريم الايات من 22 الى 58"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/019-59-98.mp3" , suwraName : "سورة مريم الايات من 59 الى 98"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/020-1-54.mp3" , suwraName : "سورة طه الايات من 1 الى 54"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/020-55-82.mp3" , suwraName : "سورة طه الايات من 55 الى 82"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/020-83-110.mp3" , suwraName : "سورة طه الايات من 83 الى 110"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/020-111-135.mp3" , suwraName : "سورة طه الايات من 111 الى 135"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/021-1-28.mp3" , suwraName : "سورة الأنبياء الايات من 1 الى 28"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/021-29-50.mp3" , suwraName : "سورة الأنبياء الايات من 29 الى 50"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/021-51-82.mp3" , suwraName : "سورة الأنبياء الايات من 51 الى 82"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/021-83-112.mp3" , suwraName : "سورة الأنبياء الايات من 83 الى 112"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/022-1-18.mp3" , suwraName : "سورة الحج الايات من 1 الى 18"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/022-19-37.mp3" , suwraName : "سورة الحج الايات من 19 الى 37"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/022-38-59.mp3" , suwraName : "سورة الحج الايات من 38 الى 59"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/022-60-78.mp3" , suwraName : "سورة الحج الايات من 60 الى 78"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/023-1-35.mp3" , suwraName : "سورة المؤمنون الايات من 1 الى 35"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/023-36-74.mp3" , suwraName : "سورة المؤمنون الايات من 36 الى 74"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/023-75-118.mp3" , suwraName : "سورة المؤمنون الايات من 75 الى 118"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/024-1-20.mp3" , suwraName : "سورة النور الايات من 1 الى 20"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/024-21-34.mp3" , suwraName : "سورة النور الايات من 21 الى 34"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/024-35-52.mp3" , suwraName : "سورة النور الايات من 35 الى 52"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/024-53-64.mp3" , suwraName : "سورة النور الايات من 53 الى 64"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/025-1-20.mp3" , suwraName : "سورة الفرقان الايات من 1 الى 20"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/025-21-52.mp3" , suwraName : "سورة الفرقان الايات من 21 الى 52"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/025-53-77.mp3" , suwraName : "سورة الفرقان الايات من 53 الى 77"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/026-1-51.mp3" , suwraName : "سورة الشعراء الايات من 1 الى 51"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/026-52-110.mp3" , suwraName : "سورة الشعراء الايات من 52 الى 110"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/026-111-180.mp3" , suwraName : "سورة الشعراء الايات من 111 الى 180"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/026-181-227.mp3" , suwraName : "سورة الشعراء الايات من 181 الى 227"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/027-1-26.mp3" , suwraName : "سورة النمل الايات من 1 الى 26"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/027-27-55.mp3" , suwraName : "سورة النمل الايات من 27 الى 55"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/027-56-81.mp3" , suwraName : "سورة النمل الايات من 56 الى 81"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/027-82-93.mp3" , suwraName : "سورة النمل الايات من 82 الى 93"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/028-1-11.mp3" , suwraName : "سورة القصص الايات من 1 الى 11"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/028-12-28.mp3" , suwraName : "سورة القصص الايات من 12 الى 28"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/028-29-50.mp3" , suwraName : "سورة القصص الايات من 29 الى 50"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/028-51-75.mp3" , suwraName : "سورة القصص الايات من 51 الى 75"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/028-76-88.mp3" , suwraName : "سورة القصص الايات من 76 الى 88"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/029-1-25.mp3" , suwraName : "سورة العنكبوت الايات من 1 الى 25"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/029-26-45.mp3" , suwraName : "سورة العنكبوت الايات من 26 الى 45"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/029-46-69.mp3" , suwraName : "سورة العنكبوت الايات من 46 الى 69"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/030-1-30.mp3" , suwraName : "سورة الروم الايات من 1 الى 30"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/030-31-53.mp3" , suwraName : "سورة الروم الايات من 31 الى 53"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/030-54-60.mp3" , suwraName : "سورة الروم الايات من 54 الى 60"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/031-1-21.mp3" , suwraName : "سورة لقمان الايات من 1 الى 21"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/031-22-34.mp3" , suwraName : "سورة لقمان الايات من 22 الى 34"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/032-1-10.mp3" , suwraName : "سورة السجدة الايات من 1 الى 10"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/032-11-30.mp3" , suwraName : "سورة السجدة الايات من 11 الى 30"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/033-1-17.mp3" , suwraName : "سورة الأحزاب الايات من 1 الى 17"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/033-18-30.mp3" , suwraName : "سورة الأحزاب الايات من 18 الى 30"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/033-31-50.mp3" , suwraName : "سورة الأحزاب الايات من 31 الى 50"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/033-51-59.mp3" , suwraName : "سورة الأحزاب الايات من 51 الى 59"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/033-60-73.mp3" , suwraName : "سورة الأحزاب الايات من 60 الى 73"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/034-1-9.mp3" , suwraName : "سورة سبأ الايات من 1 الى 9"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/034-10-23.mp3" , suwraName : "سورة سبأ الايات من 10 الى 23"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/034-24-45.mp3" , suwraName : "سورة سبأ الايات من 24 الى 45"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/034-46-54.mp3" , suwraName : "سورة سبأ الايات من 46 الى 54"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/035-1-14.mp3" , suwraName : "سورة فاطر الايات من 1 الى 14"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/035-15-40.mp3" , suwraName : "سورة فاطر الايات من 15 الى 40"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/035-41-45.mp3" , suwraName : "سورة فاطر الايات من 41 الى 45"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/036-1-27.mp3" , suwraName : "سورة يس الايات من 1 الى 27"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/036-28-59.mp3" , suwraName : "سورة يس الايات من 28 الى 59"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/036-60-83.mp3" , suwraName : "سورة يس الايات من 60 الى 83"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/037-1-21.mp3" , suwraName : "سورة الصافات الايات من 1 الى 21"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/037-22-82.mp3" , suwraName : "سورة الصافات الايات من 22 الى 82"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/037-83-144.mp3" , suwraName : "سورة الصافات الايات من 83 الى 144"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/037-145-182.mp3" , suwraName : "سورة الصافات الايات من 145 الى 182"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/038-1-20.mp3" , suwraName : "سورة ص الايات من 1 الى 20"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/038-21-51.mp3" , suwraName : "سورة ص الايات من 21 الى 51"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/038-52-88.mp3" , suwraName : "سورة ص الايات من 52 الى 88"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/039-1-7.mp3" , suwraName : "سورة الزمر الايات من 1 الى 7"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/039-8-31.mp3" , suwraName : "سورة الزمر الايات من 8 الى 31"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/039-32-52.mp3" , suwraName : "سورة الزمر الايات من 32 الى 52"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/039-53-75.mp3" , suwraName : "سورة الزمر الايات من 53 الى 75"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/040-1-20.mp3" , suwraName : "سورة غافر الايات من 1 الى 20"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/040-21-40.mp3" , suwraName : "سورة غافر الايات من 21 الى 40"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/040-41-65.mp3" , suwraName : "سورة غافر الايات من 41 الى 65"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/040-66-85.mp3" , suwraName : "سورة غافر الايات من 66 الى 85"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/041-1-8.mp3" , suwraName : "سورة فصلت الايات من 1 الى 8"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/041-9-24.mp3" , suwraName : "سورة فصلت الايات من 9 الى 24"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/041-25-46.mp3" , suwraName : "سورة فصلت الايات من 25 الى 46"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/041-47-54.mp3" , suwraName : "سورة فصلت الايات من 47 الى 54"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/042-1-11.mp3" , suwraName : "سورة الشورى الايات من 1 الى 11"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/042-12-26.mp3" , suwraName : "سورة الشورى الايات من 12 الى 26"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/042-27-50.mp3" , suwraName : "سورة الشورى الايات من 27 الى 50"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/042-51-53.mp3" , suwraName : "سورة الشورى الايات من 51 الى 53"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/043-1-23.mp3" , suwraName : "سورة الزخرف الايات من 1 الى 23"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/043-24-56.mp3" , suwraName : "سورة الزخرف الايات من 24 الى 56"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/043-57-89.mp3" , suwraName : "سورة الزخرف الايات من 57 الى 89"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/044-1-6.mp3" , suwraName : "سورة الدّخان الايات من 1 الى 6"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/044-7-59.mp3" , suwraName : "سورة الدّخان الايات من 7 الى 59"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/045-1-11.mp3" , suwraName : "سورة الجاثية الايات من 1 الى 11"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/045-12-37.mp3" , suwraName : "سورة الجاثية الايات من 12 الى 37"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/046-1-20.mp3" , suwraName : "سورة الأحقاف الايات من 1 الى 20"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/046-21-35.mp3" , suwraName : "سورة الأحقاف الايات من 21 الى 35"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/047-1-9.mp3" , suwraName : "سورة محمد الايات من 1 الى 9"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/047-10-32.mp3" , suwraName : "سورة محمد الايات من 10 الى 32"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/047-33-38.mp3" , suwraName : "سورة محمد الايات من 33 الى 38"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/048-1-17.mp3" , suwraName : "سورة الفتح الايات من 1 الى 17"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/048-18-29.mp3" , suwraName : "سورة الفتح الايات من 18 الى 29"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/049-1-13.mp3" , suwraName : "سورة الحجرات الايات من 1 الى 13"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/049-14-18.mp3" , suwraName : "سورة الحجرات الايات من 14 الى 18"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/050-1-26.mp3" , suwraName : "سورة ق الايات من 1 الى 26"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/050-27-45.mp3" , suwraName : "سورة ق الايات من 27 الى 45"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/051-1-30.mp3" , suwraName : "سورة الذاريات الايات من 1 الى 30"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/051-31-60.mp3" , suwraName : "سورة الذاريات الايات من 31 الى 60"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/052-1-23.mp3" , suwraName : "سورة الطور الايات من 1 الى 23"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/052-24-49.mp3" , suwraName : "سورة الطور الايات من 24 الى 49"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/053-1-25.mp3" , suwraName : "سورة النجم الايات من 1 الى 25"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/053-26-62.mp3" , suwraName : "سورة النجم الايات من 26 الى 62"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/054-1-8.mp3" , suwraName : "سورة القمر الايات من 1 الى 8"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/054-9-55.mp3" , suwraName : "سورة القمر الايات من 9 الى 55"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/055.mp3" , suwraName : "سورة الرحمن كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/056-1-74.mp3" , suwraName : "سورة الواقعة الايات من 1 الى 74"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/056-75-96.mp3" , suwraName : "سورة الواقعة الايات من 75 الى 96"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/057-1-15.mp3" , suwraName : "سورة الحديد الايات من 1 الى 15"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/057-16-29.mp3" , suwraName : "سورة الحديد الايات من 16 الى 29"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/058-1-13.mp3" , suwraName : "سورة المجادلة الايات من 1 الى 13"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/058-14-22.mp3" , suwraName : "سورة المجادلة الايات من 14 الى 22"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/059-1-10.mp3" , suwraName : "سورة الحشر الايات من 1 الى 10"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/059-11-24.mp3" , suwraName : "سورة الحشر الايات من 11 الى 24"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/060-1-6.mp3" , suwraName : "سورة الممتحنة الايات من 1 الى 6"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/060-7-13.mp3" , suwraName : "سورة الممتحنة الايات من 7 الى 13"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/061.mp3" , suwraName : "سورة الصف كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/062.mp3" , suwraName : "سورة الجمعة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/063.mp3" , suwraName : "سورة المنافقون كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/064.mp3" , suwraName : "سورة التغابن كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/065.mp3" , suwraName : "سورة الطلاق كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/066.mp3" , suwraName : "سورة التحريم كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/067.mp3" , suwraName : "سورة الملك كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/068.mp3" , suwraName : "سورة القلم كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/069.mp3" , suwraName : "سورة الحاقة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/070.mp3" , suwraName : "سورة المعارج كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/071.mp3" , suwraName : "سورة نوح كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/072.mp3" , suwraName : "سورة الجن كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/073.mp3" , suwraName : "سورة المزمل كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/074.mp3" , suwraName : "سورة المدثر كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/075.mp3" , suwraName : "سورة القيامة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/076.mp3" , suwraName : "سورة الإنسان كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/077.mp3" , suwraName : "سورة المرسلات كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/078.mp3" , suwraName : "سورة النبأ كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/079.mp3" , suwraName : "سورة النازعات كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/080.mp3" , suwraName : "سورة عبس كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/081.mp3" , suwraName : "سورة التكوير كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/082.mp3" , suwraName : "سورة الإنفطار كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/083.mp3" , suwraName : "سورة المطففين كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/084.mp3" , suwraName : "سورة الإنشقاق كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/085.mp3" , suwraName : "سورة البروج كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/086.mp3" , suwraName : "سورة الطارق كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/087.mp3" , suwraName : "سورة الأعلى كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/088.mp3" , suwraName : "سورة الغاشية كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/089.mp3" , suwraName : "سورة الفجر كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/090.mp3" , suwraName : "سورة البلد كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/091.mp3" , suwraName : "سورة الشمس كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/092.mp3" , suwraName : "سورة الليل كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/093.mp3" , suwraName : "سورة الضحى كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/094.mp3" , suwraName : "سورة الشرح كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/095.mp3" , suwraName : "سورة التين كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/096.mp3" , suwraName : "سورة العلق كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/097.mp3" , suwraName : "سورة القدر كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/098.mp3" , suwraName : "سورة البينة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/099.mp3" , suwraName : "سورة الزلزلة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/100.mp3" , suwraName : "سورة العاديات كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/101.mp3" , suwraName : "سورة القارعة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/102.mp3" , suwraName : "سورة التكاثر كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/103.mp3" , suwraName : "سورة العصر كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/104.mp3" , suwraName : "سورة الهمزة كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/105.mp3" , suwraName : "سورة الفيل كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/106.mp3" , suwraName : "سورة قريش كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/107.mp3" , suwraName : "سورة الماعون كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/108.mp3" , suwraName : "سورة الكوثر كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/109.mp3" , suwraName : "سورة الكافرون كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/110.mp3" , suwraName : "سورة النصر كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/111.mp3" , suwraName : "سورة المسد كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/112.mp3" , suwraName : "سورة الإخلاص كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/113.mp3" , suwraName : "سورة الفلق كاملة"),
    SheikhModel(sheikhUrl : "https://server17.mp3quran.net/tafseer/tabri/114.mp3" , suwraName : "سورة الناس كاملة"),
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: kPrimaryColor,
        title: const Text('خلاصة تفسير الطبري'),
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView.builder(
          itemCount: tafsseirList.length,
            itemBuilder: (context, index) {
             return CustomTafsseirCard(tafsseirList[index]);
            },
        ),
      ),
    );
  }
}
